spring:
  application:
    name: turbine-service

server:
  address: 0.0.0.0
  port: 8089
  error:
    whitelabel:
      enabled: false

management:
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    shutdown:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://10.10.11.70:9091/eureka}
  instance:
    ip-address: true
    
turbine:
  clusterNameExpression: new String("default")
  appConfig: user-service, order-service, item-service